import type { AgentDetectionResult, FileChange, PREvent } from '@gitgate/shared';
import type { DB } from '@gitgate/db';
import { agentIdentities } from '@gitgate/db/schema';
import { eq } from 'drizzle-orm';

const DEFAULT_EXEMPT = ['dependabot[bot]', 'renovate[bot]', 'github-actions[bot]'];

const KNOWN_BOTS: Record<string, string> = {
  'devin-ai-integration[bot]': 'devin',
  'sweep-ai[bot]': 'sweep',
  'codex[bot]': 'codex',
  'copilot-pull-request-reviewer[bot]': 'copilot',
};

const BODY_MARKERS: Array<{ pattern: RegExp; provider: string }> = [
  { pattern: /<!--\s*Generated by Claude Code\s*-->/i, provider: 'claude' },
  { pattern: /\[cursor\]/i, provider: 'cursor' },
  { pattern: /https?:\/\/(?:app\.)?devin\.ai\/sessions/i, provider: 'devin' },
  { pattern: /Co-Authored-By:\s*Claude/i, provider: 'claude' },
  { pattern: /Generated with \[Claude Code\]/i, provider: 'claude' },
];

const EMAIL_PATTERNS: Array<{ pattern: RegExp; provider: string }> = [
  { pattern: /\+claude-code@users\.noreply\.github\.com$/, provider: 'claude' },
  { pattern: /@cursor\.sh$/, provider: 'cursor' },
  { pattern: /@devin\.ai$/, provider: 'devin' },
];

export interface DetectionContext {
  db: DB;
  orgId: string;
  pr: PREvent;
  files: FileChange[];
  exemptBots: string[];
}

export async function detectAgent(ctx: DetectionContext): Promise<AgentDetectionResult> {
  const exempt = new Set([...DEFAULT_EXEMPT, ...ctx.exemptBots]);
  if (exempt.has(ctx.pr.author.login)) {
    return { detected: false, provider: 'none', confidence: 'low', signals: ['exempt-bot'] };
  }

  const signals: string[] = [];
  let provider: string | null = null;
  let confidence: AgentDetectionResult['confidence'] = 'low';

  if (ctx.pr.author.login in KNOWN_BOTS) {
    provider = KNOWN_BOTS[ctx.pr.author.login]!;
    signals.push(`bot-username:${ctx.pr.author.login}`);
    confidence = 'high';
  }

  if (ctx.pr.author.email) {
    for (const { pattern, provider: p } of EMAIL_PATTERNS) {
      if (pattern.test(ctx.pr.author.email)) {
        provider ??= p;
        signals.push(`committer-email:${p}`);
        confidence = 'high';
      }
    }
  }

  for (const { pattern, provider: p } of BODY_MARKERS) {
    if (pattern.test(ctx.pr.body)) {
      provider ??= p;
      signals.push(`body-marker:${p}`);
      if (confidence !== 'high') confidence = 'high';
    }
  }

  // Custom agent identities registered in the DB
  const customs = await ctx.db
    .select()
    .from(agentIdentities)
    .where(eq(agentIdentities.orgId, ctx.orgId));
  for (const c of customs) {
    const rules = JSON.parse(c.matchRules) as {
      committerEmails?: string[];
      botUsernames?: string[];
      prBodyPatterns?: string[];
    };
    if (rules.botUsernames?.includes(ctx.pr.author.login)) {
      provider ??= c.provider;
      signals.push(`custom-bot:${c.provider}`);
      confidence = 'high';
    }
    if (ctx.pr.author.email && rules.committerEmails?.some((p) => matchEmail(p, ctx.pr.author.email!))) {
      provider ??= c.provider;
      signals.push(`custom-email:${c.provider}`);
      confidence = 'high';
    }
    for (const re of rules.prBodyPatterns ?? []) {
      try {
        if (new RegExp(re).test(ctx.pr.body)) {
          provider ??= c.provider;
          signals.push(`custom-body:${c.provider}`);
          if (confidence !== 'high') confidence = 'medium';
        }
      } catch {
        // ignore bad regex
      }
    }
  }

  // Heuristics — only kick in when we have no definitive signal yet
  if (!provider) {
    const heuristic = computeHeuristics(ctx);
    if (heuristic.score >= 2) {
      provider = 'unknown-agent';
      signals.push(...heuristic.signals);
      confidence = heuristic.score >= 3 ? 'medium' : 'low';
    }
  }

  return {
    detected: !!provider,
    provider: provider ?? 'none',
    confidence,
    signals,
  };
}

function matchEmail(pattern: string, email: string): boolean {
  if (pattern.startsWith('*')) return email.endsWith(pattern.slice(1));
  return email === pattern;
}

interface HeuristicResult {
  score: number;
  signals: string[];
}

function computeHeuristics(ctx: DetectionContext): HeuristicResult {
  const signals: string[] = [];
  let score = 0;

  // Tight commit timing within 2s spread is captured upstream — we only see the PR.
  // Approximations using the diff:
  const additions = ctx.files.reduce((s, f) => s + f.additions, 0);
  const deletions = ctx.files.reduce((s, f) => s + f.deletions, 0);
  if (additions > 0 && deletions === 0 && additions > 200) {
    signals.push('high-additions-no-deletions');
    score += 1;
  }
  if (
    ctx.pr.title.match(/^(feat|fix|chore|docs|refactor|test|ci|build)(\(.+\))?:/i) &&
    ctx.pr.body.length > 0
  ) {
    signals.push('conventional-template');
    score += 1;
  }
  if (/\bAUTO-GENERATED\b/i.test(ctx.pr.body) || /\bautogenerated\b/i.test(ctx.pr.body)) {
    signals.push('autogen-marker');
    score += 2;
  }
  return { score, signals };
}
