export interface HeaderOptions {
  sourcePath?: string;
  url?: string;
}

/**
 * Generate the YAML file header that warns the user not to edit the file
 * by hand and points them back to the TypeScript source.
 */
export function generateHeader(options: HeaderOptions = {}): string {
  const lines = [
    '# AUTO-GENERATED by @rehearse/ci. Do not edit by hand.',
    `# Run: rh ci compile`,
  ];
  if (options.sourcePath) {
    lines.push(`# Source: ${options.sourcePath}`);
  }
  if (options.url) {
    lines.push(`# Docs: ${options.url}`);
  }
  return `${lines.join('\n')}\n\n`;
}
