#!/usr/bin/env node
/**
 * Cross-language bench: runs each app in examples/ locally and remotely
 * (cold + warm), times each, prints a markdown table to stdout.
 *
 * Usage:
 *   $env:REHEARSE_TOKEN = "rh_pro_live_..."
 *   node bench/examples-bench.mjs
 *
 * --only <app>        only run the named app (e.g. node-app)
 * --skip-local        skip local runs (e.g. when host doesn't have dotnet)
 * --skip-remote       skip remote runs (e.g. when offline)
 * --runner-cli <path> point at a built CLI; defaults to runner/dist/cli.js
 */
import { spawnSync } from 'node:child_process';
import { existsSync, readdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(here, '..');
const examplesDir = resolve(repoRoot, 'examples');

const args = process.argv.slice(2);
const arg = (k, d) => {
  const i = args.indexOf(k);
  return i > -1 ? args[i + 1] : d;
};
const has = (k) => args.includes(k);

const only = arg('--only', null);
const skipLocal = has('--skip-local');
const skipRemote = has('--skip-remote');
const runnerCli = arg('--runner-cli', resolve(repoRoot, 'runner', 'dist', 'cli.js'));

if (!skipRemote && !process.env.REHEARSE_TOKEN) {
  console.error('REHEARSE_TOKEN required for remote runs (or pass --skip-remote)');
  process.exit(2);
}
if (!existsSync(runnerCli)) {
  console.error(`runner CLI not found at ${runnerCli}; run \`pnpm --filter @rehearse/runner build\``);
  process.exit(2);
}

// Apps we skip on Pro and document why. The `--only` override still runs
// these so you can confirm the limitation hasn't changed.
const PRO_UNSUPPORTED = {
  'php-app': 'PHP runtime not on Sprites; composer not found; shivammathur/setup-php@v2 needs apt-get',
  'python-api': 'declares `services: postgres` which needs Docker on the sprite (not available in Pro v0)',
};

const apps = readdirSync(examplesDir, { withFileTypes: true })
  .filter((d) => d.isDirectory() && !d.name.startsWith('.') && d.name !== 'node_modules')
  .map((d) => d.name)
  .filter((name) => existsSync(resolve(examplesDir, name, '.github', 'workflows', 'ci.yml')))
  .filter((name) => (only ? name === only : true))
  .filter((name) => only || !PRO_UNSUPPORTED[name]);

if (!only) {
  for (const [app, reason] of Object.entries(PRO_UNSUPPORTED)) {
    console.error(`[skip] ${app}: ${reason}`);
  }
}

if (apps.length === 0) {
  console.error('no apps with .github/workflows/ci.yml found');
  process.exit(2);
}

/**
 * Run a command, return {ms, exitCode, stderr-tail}. Doesn't stream;
 * captures everything and returns. We only need the timings.
 */
function timeRun(cmd, cmdArgs, opts) {
  const start = Date.now();
  const r = spawnSync(cmd, cmdArgs, {
    cwd: opts.cwd,
    env: { ...process.env, ...(opts.env ?? {}) },
    encoding: 'utf-8',
    maxBuffer: 64 * 1024 * 1024,
    timeout: 600_000,
  });
  const ms = Date.now() - start;
  const stderrTail = (r.stderr ?? '').split('\n').filter(Boolean).slice(-3).join(' / ');
  return { ms, exit: r.status ?? -1, tail: stderrTail };
}

const results = [];

for (const app of apps) {
  const cwd = resolve(examplesDir, app);
  const workflow = '.github/workflows/ci.yml';
  console.error(`\n=== ${app} ===`);

  let local = null;
  let remoteCold = null;
  let remoteWarm = null;

  if (!skipLocal) {
    console.error('  [local]   running...');
    local = timeRun(process.execPath, [runnerCli, 'run', workflow, '--quiet'], { cwd });
    console.error(`  [local]   ${local.ms}ms exit=${local.exit}`);
  }

  if (!skipRemote) {
    console.error('  [remote cold]  running...');
    remoteCold = timeRun(process.execPath, [runnerCli, 'run', '--remote', workflow], { cwd });
    console.error(`  [remote cold]  ${remoteCold.ms}ms exit=${remoteCold.exit}`);

    console.error('  [remote warm]  running...');
    remoteWarm = timeRun(process.execPath, [runnerCli, 'run', '--remote', workflow], { cwd });
    console.error(`  [remote warm]  ${remoteWarm.ms}ms exit=${remoteWarm.exit}`);
  }

  results.push({ app, local, remoteCold, remoteWarm });
}

// Markdown report to stdout
const fmt = (r) => (r ? `${(r.ms / 1000).toFixed(1)}s${r.exit !== 0 ? ` ⚠️ exit=${r.exit}` : ''}` : '—');
const speedup = (a, b) => (a && b && a.ms > 0 && b.ms > 0 ? `${(a.ms / b.ms).toFixed(1)}×` : '—');

console.log('\n# Cross-language example bench');
console.log('');
console.log('Each row: same workflow YAML, executed three ways. Lower = faster.');
console.log('');
console.log('| App | Local (host) | Remote cold | Remote warm | Cold→warm speedup |');
console.log('|---|---:|---:|---:|---:|');
for (const r of results) {
  console.log(
    `| \`${r.app}\` | ${fmt(r.local)} | ${fmt(r.remoteCold)} | ${fmt(r.remoteWarm)} | ${speedup(r.remoteCold, r.remoteWarm)} |`,
  );
}
console.log('');
console.log(`Generated by \`bench/examples-bench.mjs\` on ${new Date().toISOString()}.`);
