#!/usr/bin/env node
/**
 * `runner` CLI — local-first GitHub Actions runner.
 */
import { Command } from 'commander';
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import pc from 'picocolors';
import { run } from './orchestrator.js';
import { watchWorkflow } from './watch.js';
import type { BackendName } from './types.js';

const program = new Command();

program
  .name('runner')
  .description('Local-first runner for GitHub Actions workflows')
  .version('0.1.0');

program
  .command('run <workflow>', { isDefault: true })
  .description('Run a GitHub Actions workflow on this machine')
  .option('-j, --job <name>', 'restrict to a single job (matrix variants of that job all run)')
  .option('-b, --backend <type>', 'host | container | auto', 'auto')
  .option('-p, --max-parallel <n>', 'max concurrent jobs', (v) => Number(v))
  .option('-c, --cwd <dir>', 'working directory (default: inferred from workflow path)')
  .option('--fail-fast', 'cancel sibling jobs on first failure')
  .option('--quiet', 'minimal output (machine-readable result only)')
  .option('--bench', 'output a single JSON line for benchmarking')
  .option('--env-file <file>', 'load env vars from file (KEY=VALUE per line)')
  .action(async (workflow, opts) => {
    const env = opts.envFile ? loadEnvFile(opts.envFile) : {};
    const result = await run({
      workflowPath: workflow,
      cwd: opts.cwd,
      jobFilter: opts.job,
      backend: opts.backend === 'auto' ? 'auto' : (opts.backend as BackendName),
      maxParallel: opts.maxParallel,
      failFast: opts.failFast,
      verbosity: opts.quiet || opts.bench ? 'quiet' : 'normal',
      env,
      secrets: env,
    });
    if (opts.bench) {
      process.stdout.write(JSON.stringify({
        status: result.status,
        durationMs: result.durationMs,
        jobs: result.jobs.map((j) => ({ id: j.jobId, status: j.status, ms: j.durationMs })),
      }) + '\n');
    }
    process.exit(result.status === 'failure' ? 1 : 0);
  });

program
  .command('watch <workflow>')
  .description('Re-run the workflow on file changes (inner-loop dev tool)')
  .option('-j, --job <name>', 'restrict to a single job')
  .option('-b, --backend <type>', 'host | container | auto', 'auto')
  .option('-p, --max-parallel <n>', 'max concurrent jobs', (v) => Number(v))
  .option('-c, --cwd <dir>', 'working directory')
  .option('--env-file <file>', 'load env vars from file')
  .action(async (workflow, opts) => {
    const env = opts.envFile ? loadEnvFile(opts.envFile) : {};
    await watchWorkflow({
      workflowPath: workflow,
      cwd: opts.cwd,
      jobFilter: opts.job,
      backend: opts.backend === 'auto' ? 'auto' : (opts.backend as BackendName),
      maxParallel: opts.maxParallel,
      verbosity: 'normal',
      env,
      secrets: env,
    });
  });

program
  .command('install-hook')
  .description('Install a pre-push git hook that runs the workflow before letting you push')
  .option('-w, --workflow <path>', '.github/workflows/<name>.yml to run', '.github/workflows/ci.yml')
  .option('-j, --job <name>', 'restrict to one job (recommended for speed)')
  .action(async (opts) => {
    const repoRoot = process.cwd();
    const hooksDir = resolve(repoRoot, '.git', 'hooks');
    if (!existsSync(hooksDir)) {
      console.error(pc.red('✗ .git/hooks not found — run from inside a git repo.'));
      process.exit(2);
    }
    const hookPath = resolve(hooksDir, 'pre-push');
    const body = `#!/usr/bin/env bash
# Auto-generated by 'runner install-hook'. Edit or delete to disable.
exec npx runner run ${JSON.stringify(opts.workflow)}${opts.job ? ` --job ${JSON.stringify(opts.job)}` : ''} --fail-fast
`;
    writeFileSync(hookPath, body, 'utf-8');
    try {
      mkdirSync(hooksDir, { recursive: true });
      // Best-effort chmod on Unix
      if (process.platform !== 'win32') {
        const { chmodSync } = await import('node:fs');
        chmodSync(hookPath, 0o755);
      }
    } catch { /* non-fatal */ }
    console.log(pc.green('✓ pre-push hook installed at ') + pc.cyan(hookPath));
  });

function loadEnvFile(path: string): Record<string, string> {
  const out: Record<string, string> = {};
  if (!existsSync(path)) return out;
  const body = readFileSync(path, 'utf-8');
  for (const line of body.split(/\r?\n/)) {
    const t = line.trim();
    if (!t || t.startsWith('#')) continue;
    const eq = t.indexOf('=');
    if (eq <= 0) continue;
    const k = t.slice(0, eq).trim();
    let v = t.slice(eq + 1).trim();
    if ((v.startsWith('"') && v.endsWith('"')) || (v.startsWith("'") && v.endsWith("'"))) v = v.slice(1, -1);
    out[k] = v;
  }
  return out;
}

program.parseAsync(process.argv).catch((err: unknown) => {
  console.error(pc.red('✗ ' + ((err as Error).message ?? String(err))));
  process.exit(1);
});
